article/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = "article"

urlpatterns = [
    path('dashboard/', views.dashboard,name= "dashboard" ),
    path('addarticle/', views.addArticle,name= "addarticle" ),
    path('article/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.updateArticle, name="update"),
    path('delete/<int:id>', views.deleteArticle, name="delete"),
    path('', views.articles, name="articles"),

]

blog/urls.py
from django.contrib import admin
from django.urls import path,include

from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),

]

admin.site.site_title = "YB BLOG Admin"
admin.site.site_header = "YB BLOG Admin Panel"
admin.site.index_title = "YB Blog Admin Panele Hoşgeldiniz"

user/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register" ),
    path('login/', views.loginUser, name="login" ),
    path('logout/', views.logoutUser, name="logout" ),

]

article/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name="Yazar")
    title = models.CharField(max_length=50,verbose_name="Başlık")
    content = models.TextField(verbose_name="Detaylı İçerik")
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    def __str__(self):
        return self.title

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content"]     

user/forms.py
from typing import Any
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label="Kullanıcı Adı")
    password = forms.CharField(label="Parola",widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "Kullanıcı Adı")
    password = forms.CharField(max_length=20,label = "Parola",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Parolayı Doğrula",widget = forms.PasswordInput)
    
    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar Eşleşmiyor")

        values = {
            "username" : username,
            "password" : password
        }
        return values
    

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from .forms import ArticleForm
from django.contrib import messages
from .models import Article
from django.contrib.auth.decorators import login_required


# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"articles.html",{"articles":articles})


    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})

def index(request):
    return render(request,"index.html")

def about(request):

    return render(request,"about.html")

@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context={
        "articles":articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request,"Makale Başarıyla Oluşturuldu.")
        return redirect("article:dashboard")


    return render(request,"addarticle.html",{"form":form})

@login_required(login_url="user:login")
def detail(request,id):
    #article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article,id=id)
    return render(request,"detail.html",{"article":article})

@login_required(login_url="user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None,instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request,"Makale Başarıyla Güncellendi.")
        return redirect("article:dashboard")
     
     

    return render(request,"update.html",{"form":form})

@login_required(login_url="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()

    messages.success(request,"Makale Başarıyla Silindi.")

    return redirect("article:dashboard")

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages

# Create your views here.

def register(request):

     form = RegisterForm(request.POST or None)
     if form.is_valid():
      username = form.cleaned_data.get("username")
      password = form.cleaned_data.get("password")

      newUser = User(username =username)
      newUser.set_password(password)

      newUser.save()
      login(request,newUser)
      messages.info(request,"Başarıyla kayıt oldunuz...")

      return redirect("index")
     context = {
            "form" : form
        }
     return render(request,"register.html",context)

 
# Login ----------------- Başlangıç ----------------

def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"login.html",context)

        messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)

# Login -------------------------- Bitiş ---------------------        


def logoutUser(request):
    logout(request)
    messages.success(request,"Başarıyla çıkış yaptınız")
    return redirect("index")



   



    

    
        

    
    

              





    

templates/about.html
{% extends 'layout.html' %}

{% block body %}

<h3>Hakkımızda</h3>
<hr>
<p>
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
</p>
    
{% endblock %}

templates/addarticle.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block body %}



<div class="row">
    <div class="col-md-6 offset-md-3">
        <h4>Makale Oluşturun</h4>
        <hr>
        <form method="post">
            {% csrf_token %}
        
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Makale Oluştur</button>
            <br><br>
        </form>




    </div>


</div>






{% endblock %}

templates/articles.html
{% extends 'layout.html' %}

{% block body %}

<h3>Makaleler</h3>
<hr>

<div class="container">
    
    <div class="col-md-10 offset-md-3">
        <div class="form-inline">
            <form>
                 {% csrf_token %} 
             <input class="form-control mr-1" type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara...">
              <button type="submit" class="btn btn-danger">Ara</button>
            </form>
      </div>
    </div>
    <br>

{% if articles %}
<ul class="list-group">

    {% for article in articles %}
    
    <li class="list-group-item"><a href="{% url 'article:detail' article.id %}">{{article.title}} </a></li>
    
</ul>

 

    
 {% endfor %}
    
{% else %}
<div class="alert alert-danger">
    Makale bulunamadı...

    
</div>

    
{% endif %}
    
{% endblock %}

templates/dashboard.html
{% extends 'layout.html' %}

{% block body %}

<h3>Kontrol Paneli</h3>
<hr>

<p>
    Hoşgeldiniz, {{request.user.username}}
</p>
<hr>
<a class="btn btn-danger" href="{% url 'article:addarticle'%}">Makale Ekle</a>
<br>
<hr>

{% if articles %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Başlık</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarih</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
      </tr>
    </thead>
    <tbody>
        {% for article in articles %}
    <tr>
        <th scope="row">{{article.id}}</th>
        <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
        <td>{{article.author.username}}</td>
        <td>{{article.created_date}}</td>
        <td><a class="btn btn-danger" href="{% url 'article:update' article.id %}">Güncelle</a></td>
        <td><a class="btn btn-danger" href="{% url 'article:delete' article.id %}">Sil</a></td>
    </tr>
            
        {% endfor %}
      
    </tbody>
  </table>
    
{% else %}
<div class="alert alert-danger">
    Henüz bir makaleniz bulunmuyor...
 

</div>
    
{% endif %}






    
{% endblock %}

templates/detail.html
{% extends 'layout.html' %}

{% block body %}


{% include 'includes/posttemplate.html'   %}
    
{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'index'%}">YB Blog</a>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'about'%}">Hakkımızda<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'article:articles'%}">Makaleleler<span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'article:dashboard'%}">Kontrol Paneli<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:logout'%}">Çıkış Yap<span class="sr-only">(current)</span></a>
      </li>
      {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:login'%}">Giriş Yap<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:register'%}">Kayıt Ol<span class="sr-only">(current)</span></a>
      </li>
      {% endif %}




    </ul>
  </div>
</nav>

templates/includes/posttemplate.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Post - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    </head>
    <body>

        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">by {{article.author.username}} | {{article.created_date}}</div>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{article.content}}</p>
                            
                        </section>
                    </article>

                                </div>
                               
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                
                </div>
            </div>
        </div>       
    </body>
</html>

templates/index.html
{% extends 'layout.html' %}

{% block body %}

<div class="jumbotron text-center">
    <h3>Yazılım bilimi bloğuna hoşgeldiniz.</h3>
    <p>Bu blogta yazılımcılar için blog içerikleri paylaşılıyor.</p>

</div>

<p>
    {% if request.user.is_authenticated %}
    Giriş Yapılmış, {{request.user.username}}
        
    {% else %}
    Giriş Yapılmamış
        
    {% endif %}
</p>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>YBBLOG</title>
</head>
<body>

    {% include "includes/navbar.html"   %}

    

    <div style="margin-top: 50px;" class="container">

    {% if messages %}
    
     {% for message in messages %}

     {% if message.tags == "info" %}
      <div class="alert alert-danger">{{ message }}</div>
        
     {% else %}
      <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        
    {% endif %}
  
    {% endfor %}
    
    {% endif %}

        {% block body %}
            
        {% endblock %}






    </div>
 

    
    
    <script src="{% static 'js/jquery-3.2.1.min.js'  %}"></script>
    <script src="{% static 'js/bootstrap.min.js'  %}"></script>
</body>
</html>

templates/login.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block body %}



<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
        
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Giriş Yap</button>
        </form>




    </div>


</div>






{% endblock %}

templates/register.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
        
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Kayıt Ol</button>
        </form>




    </div>


</div>
    
{% endblock %}

templates/update.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block body %}



<div class="row">
    <div class="col-md-6 offset-md-3">
        <h4>Makale Güncelleyin</h4>
        <hr>
        <form method="post">
            {% csrf_token %}
        
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Makale Güncelle</button>
        </form>




    </div>


</div>

{% endblock %}